-module(scripts).
-export([get_scripts_list/0]).

get_scripts_list() ->
    [
     "external/jquery.js",
     "external/jquery.cookie.js",
     "external/jquery.bgiframe.js",
     "external/jquery.browser.js",
     "external/jquery.history.js",
     "external/jquery.mousewheel.js"
     "external/jquery.dynDateTime.js",
     "external/jquery-ui-datePicker.min.js",
     "external/jscolor.js",
     "external/hashtable.js",
     "external/silverlight.js",
     "services/json.js",
     "common/base64.js",
     "common/debug.js",
     "common/function.js",
     "common/object.js",
     "common/guid.js",
     "common/method-interceptor.js",
     "common/proxy-interceptor.js",

     "common/data/array.js",
     "common/data/array.linq.js",

     "common/auto.event.js",
     "common/auto.property.js",

     "common/trait.js",
     "common/data/array.observable.js",
     "common/data/array.sorted.js",
     "common/data/array.tracking.js",

     "common/inheritance.js",
     "common/string-builder.js",
     "common/regexp.js",
     "common/string.js",
     "common/boolean.js",
     "common/date.js",
     "common/culture.js",
     "common/dom.js",

     "core/queue-processor.js",
     "data/dto-processor.js",
     "data/repository.js",
     "data/entity.js",
     "data/entity-set.js",
     "data/data-filter.js",
     "data/data-source.js",
     "data/data-source.filtered.js",
     "data/data-source.paginated.js",
     "data/data-source.ordered.js",

     "history/history.observer.js",
     "history/history.base-observer.js",
     "history/history.default-observer.js",
     "history/history.data-source.js",
     "history/history.observable-list.js",
     "history/history.boolean.js",
     "history/history.date.js",

     "core/keys.js",
     "core/ui/text-measurer.js",
     "core/ui/css-rules.js",
     "core/ui/dimension-unit.js",
     "core/ui/rect.js",
     "core/page-uri.js",
     "core/application-context.js",
     "core/application.js",
     "core/configuration.js",
     "core/ui/layout-engines/layout-factory.js",
     "core/ui/depth_manager.js",
     "core/ui/color.js",
     "core/ui/layout-engines/base-layout.js",
     "core/ui/layout-engines/stack-layout.js",
     "core/ui/layout-engines/*.js",
     "core/ui/control.js",
     "core/ui/controls-collection.js",
     "core/ui/controls-factory.js",
     "core/ui/template.js",
     "core/ui/base-list-data-control.js",

     {controls, [
		 {control, "Panel"},
		 {control, "Repeater"},
		 {control, "Button"},
		 {control, "Checkbox"},
		 {control, "CheckList"},
		 {control, "CollapsablePanel"},
		 {control, "Container"},
		 {control, "DataGrid"},
		 {control, "DatePicker"},
		 {control, "DropDownList"},
		 {control, "FileUpload"},
		 {control, "PhotoUpload"},
		 {control, "Image"},
		 {control, "Label"},
		 {control, "Link"},
		 {control, "ListView"},
		 {control, "Literal"},
		 {control, "Page"},
		 {control, "Frame"},
		 {control, "Form"},
		 {control, "Pager"},
		 {control, "Popup"},
		 {control, "ScrollablePanel"},
		 {control, "Silverlight"},
		 {control, "Slider"},
		 {control, "Table"},
		 {control, "TabPanel"},
		 {control, "TextBox"},
		 {control, "TextEditor"},
		 {control, "Tree"},
		 {control, "Tooltip"},
		 {control, "Wizard"},
		 {control, "ColorPicker"},
		 {control, "MultiView"}
		]
     ].
